### ISSUE TITLE
Unable to guess how to get a Doctrine instance from the request information for parameter

### ISSUE THREAD

**Issue by xvilo** [neoshadybeat/hashidsBundle#16]
Getting this `Unable to guess how to get a Doctrine instance from the request information for parameter` error when navigating to `/timer/edit/Lvg` not sure what i'm doing wrong with this code: 

```php
    /**
     * @Route("/timer/edit/{hashid}", requirements={"hashid"="[A-Za-z0-9_-]+"}, name="timer_edit")
     * @ParamConverter("timer", class="App\Entity\Timer")
     * @param Timer $timer
     * @return \Symfony\Component\HttpFoundation\RedirectResponse|\Symfony\Component\HttpFoundation\Response
     * @throws \Exception
     */
    public function editTimer(Timer $timer)
    {
        die(var_dump($timer->getId()));
    }
```

Edit:
Using latest symfony 4.2

**Comment by PhilETaylor** [comment]
This is because `DoctrineParamConverter` class made the `getIdentifier` method [private instead of protected 4 YEARS AGO](https://github.com/Cloudstek/SensioFrameworkExtraBundle/commit/77193bac3d13ba93517385efc09e531a69d7f5e4#diff-73318e00ccc7f44ec75987d95f949a74R99) so its no longer possible to overlay the getIdentifier method in the parent class.

**Comment by PhilETaylor** [comment]
I just pushed a fix to my own fork, that works... https://github.com/PhilETaylor/hashidsBundle/commit/c9aa6ab85aad1b26502bac404c58adadff50747b
